"""empty message

Revision ID: 2d22090b63f1
Revises: 5b9f3cf61117
Create Date: 2020-09-05 19:05:35.278291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d22090b63f1'
down_revision = '5b9f3cf61117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('firebase_id')
    )
    op.add_column('sale_items', sa.Column('seller_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'seller_username')
    op.drop_table('users')
    # ### end Alembic commands ###
