"""empty message

Revision ID: a8c7f1d6e06c
Revises: 2d22090b63f1
Create Date: 2020-09-05 19:07:08.165924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c7f1d6e06c'
down_revision = '2d22090b63f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'cost',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sale_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sale_items', 'seller_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'seller_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sale_items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sale_items', 'cost',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
